qtab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('questionnaires.urls')),
    url(r'^questionnaires/', include('questionnaires.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionnaires/urls.py
from axes.decorators import watch_login
from django.conf.urls import url
from django.contrib.auth.views import password_change, password_reset,password_reset_complete, password_reset_confirm, password_reset_done

from . import views, customviews


app_name = 'questionnaires'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', watch_login(views.LoginView.as_view()), name='loginform'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^locked/$', views.locked_out, name='locked_out'),
    url('^password_change/$', password_change, {'template_name': 'admin/password_change_form.html', 'post_change_redirect': 'questionnaires:index'}, name='password_change'),
    url('^password_reset/$', password_reset, {'post_reset_redirect': 'questionnaires:index'},name='password_reset'),
    url('^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url('^reset/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, {'template_name':'admin/password_reset_email.html'}, name='password_reset_confirm'),
    url('^reset/done/$', password_reset_complete, {'template_name':'admin/password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^results/$', views.ResultFilterView.as_view(), name='results'),
    url(r'^reports/$', views.SubjectReportView.as_view(), name='reports'),
    url(r'^visits/$', views.VisitView.as_view(), name='visits'),
    url(r'^(?P<subjectid>[0-9]+)/download/$', views.download_report, name='download'),
    url(r'^(?P<pk>[0-9]+)/qintro/$', views.DetailView.as_view(), name='qintro'),
    url(r'^(?P<pk>[0-9]+)/q/$', views.load_questionnaire, name='q'),
    url(r'^(?P<token>[0-9]+)/deleteresults/$', views.TestResultDelete.as_view(), name='deleteresults'),
    url(r'^custom/(?P<code>[0-9A-Za-z\-]+)/$', customviews.baby_measurements, name='Wav1P08b'),
    url(r'^custom2/(?P<code>[0-9A-Za-z\-]+)/$', customviews.maturation, name='Wav1P12'),
    url(r'^custom3/(?P<code>[0-9A-Za-z\-]+)/$', customviews.familyHistoryPart1, name='Wav1P16A'),
    url(r'^custom4/(?P<code>[0-9A-Za-z\-]+)/$', customviews.familyHistoryPart2, name='Wav1P16B'),
    url(r'^custom5/(?P<code>[0-9A-Za-z\-]+)/$', customviews.familyHistoryPart2, name='Wav1P16C'),

]

questionnaires/views.py
import copy
import operator
import os
import re
import time
from collections import OrderedDict
from datetime import datetime

from axes.utils import reset
from django.conf import settings
from django.contrib.auth import REDIRECT_FIELD_NAME, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import password_change
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
from django.core.urlresolvers import reverse_lazy, reverse
from django.db import IntegrityError
from django.db.models import Count
from django.db.models import Q
from django.forms import formset_factory
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect, resolve_url, render_to_response
from django.template import RequestContext
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from formtools.wizard.views import SessionWizardView
from ipware.ip import get_ip

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
try:
    import urlparse
except ImportError:
    from urllib import parse as urlparse # python3 support
# import the logging library
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)
###Local classes
from .models import Questionnaire, Choice, TestResult, SubjectQuestionnaire,Category,SubjectVisit,Question
from .forms import AxesCaptchaForm, AnswerForm, TestResultDeleteForm, BaseQuestionFormSet, replaceTwinNames
from .tables import FilteredSingleTableView, TestResultTable,SubjectQuestionnaireTable,SubjectVisitTable
from .filters import TestResultFilter,SubjectQuestionnaireFilter,SubjectVisitFilter



## Login
class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    template_name = 'questionnaires/index.html'
    success_url = '/questionnaires'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.get_user()
        if user is not None:
            msg = 'User: %s' % user
            if user.is_active:
                login(self.request, user)
                msg = '% has logged in' % msg
                logger.info(msg)
            else:
                # Return a 'disabled account' error message
                form.add_error = 'Your account has been disabled. Please contact admin.'
                msg = '% has disabled account' % msg
                logger.warning(msg)

        else:
            # Return an 'invalid login' error message.
            form.add_error = 'Login credentials are invalid. Please try again'
            msg = 'Login failed with invalid credentials'
            logger.error(msg)

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        self.check_and_delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def form_invalid(self, form):
        """
        The user has provided invalid credentials (this was checked in AuthenticationForm.is_valid()). So now we
        set the test cookie again and re-render the form with errors.
        """
        self.set_test_cookie()
        return super(LoginView, self).form_invalid(form)

    def set_test_cookie(self):
        self.request.session.set_test_cookie()

    def check_and_delete_test_cookie(self):
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
            return True
        return False

    def get_success_url(self):
        if self.success_url:
            redirect_to = self.success_url
        else:
            redirect_to = self.request.POST.get(
                self.redirect_field_name,
                self.request.GET.get(self.redirect_field_name, ''))

        netloc = urlparse.urlparse(redirect_to)[1]
        if not redirect_to:
            redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
        # Security check -- don't allow redirection to a different host.
        elif netloc and netloc != self.request.get_host():
            redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
        return redirect_to
        #return reverse(redirect_to)


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    #template_name = 'questionnaires/index.html'
    successurl = '/questionnaires'

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(self.successurl)

def locked_out(request):
    if request.POST:
        form = AxesCaptchaForm(request.POST)
        if form.is_valid():
            ip = get_ip(request)
            if ip is not None:
                msg = "User locked out with IP address=%s" % ip
                logger.warning(msg)
                reset(ip=ip)

            return HttpResponseRedirect(reverse_lazy('questionnaires:index'))
    else:
        form = AxesCaptchaForm()

    return render(request,'questionnaires/locked.html', dict(form=form))

def change_password(request):
    template_response = password_change(request)
    # Do something with `template_response`
    return template_response

def csrf_failure(request, reason=""):
    ctx = {'title': 'CSRF Failure', 'message': 'Your browser does not accept cookies and this can be a problem in ensuring a secure connection.'}
    template_name= 'admin/csrf_failure.html'
    return render_to_response(template_name, ctx)
###########################################################################################

class IndexView(generic.ListView):
    template_name = 'questionnaires/index.html'
    context_object_name = 'questionnaire_list'
    raise_exception = True

    def get_queryset(self):
        return Questionnaire.objects.order_by('order').order_by('code')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        user = self.request.user
        rlist = []
        qlist = {}
        cat1 = None
        if user is not None and user.is_active:
            # set defaults
            cat1 = Category.objects.get(name='Wave 1')  # Wave 1
            catlist = [c for c in Category.objects.filter(name__icontains='all')]  # include ALL
            qlist = self.get_queryset().distinct('code')
            #user_results = user.subjectquestionnaire_set.all() #SubjectQuestionnaire.objects.filter(subject=user)
            rlist = user.subjectquestionnaire_set.distinct('questionnaire')

            if not user.is_superuser:
                visit = SubjectVisit.objects.filter(subject=user)
                #If missing, create visit and set to first category
                if len(visit)==0:
                    visit = SubjectVisit(subject=user, category=cat1, date_visit=datetime.now())
                    visit.save()
                else:
                    visit = visit[0]
                cat1 = visit.category
                catlist.append(cat1)
                usergrouplist = user.groups.values_list('name')

                rlist = rlist.filter(questionnaire__category__in=catlist)
                qlist = qlist.filter(active=True).filter(category__in=catlist).filter(group__name__in=usergrouplist)
            #exclude completed
            for r in rlist:
                qlist = qlist.exclude(pk=r.questionnaire.id)
        #Reorder list by 'order' to allow manual override
        qlist = sorted(qlist, key=operator.attrgetter('order'))
        rlist = sorted(rlist, key=operator.attrgetter('date_stored'), reverse=True)
        # Reset session conditional data
        if self.request.session.get('conditionals'):
            #print("DEBUG: FORM_INITIAL: Reset conditionals")
            self.request.session['conditionals'] = {}


        context['questionnaire_list'] = qlist
        context['result_list']= rlist
        context['visit'] = cat1

        return context


# Questionnaire Intro page
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Questionnaire
    template_name = 'questionnaires/intro.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

################REPORT TABLES ##########################################
##Reports
class SubjectReportView(LoginRequiredMixin, FilteredSingleTableView):
    template_name = 'questionnaires/results_summary.html'
    model = SubjectQuestionnaire
    table_class = SubjectQuestionnaireTable
    filter_class = SubjectQuestionnaireFilter
    raise_exception = True

    def get_queryset(self):
        return SubjectQuestionnaire.objects.order_by('questionnaire__code')

    def get_context_data(self, **kwargs):
        context = super(SubjectReportView, self).get_context_data(**kwargs)
        context['title'] = "Subject Reports"
        return context


##Results
class ResultFilterView(LoginRequiredMixin, FilteredSingleTableView):
    template_name = 'questionnaires/results_summary.html'
    model = TestResult

questionnaires/templates/questionnaires/base.html
<!DOCTYPE html>
{% load i18n %}

<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>QTAB {% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="icon" href="{% static "qtab/img/Panda.ico" %}" type="image/png"/>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "qtab/css/style.css" %}"/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
    <script type="text/javascript" src="{% static "qtab/js/jquery-1.12.3.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

 {% block head %}{% endblock %}
  </head>
  <body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
		<div class="navbar-header">
		  <a  class="navbar-brand" href="/questionnaires/">
		  <img src="{% static 'qtab/img/Panda.ico' %}" width="100px" alt="QTAB"/></a>
		</div>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
               <li><a href="{% url 'questionnaires:index' %}" class="ui-btn-active">Home</a></li>
                {% if user.is_staff %}
		            {% include "questionnaires/navlinks.html" %}
                {% endif %}
          </ul>
		  <div class="navbar-right">
            <p>Welcome, {{ user.first_name }}
                <!--<a class="btn btn-warning" href="{% url 'questionnaires:password_change' %}">Change password</a>-->
            <a id="logoutbtn" class="btn btn-danger" href="{% url 'questionnaires:logout' %}">Logout</a></p>
          </div>
        {% else %}
          {% if form.non_field_errors %}
            <p class="col-sm-4 alert alert-danger">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
                <a href="{% url 'questionnaires:password_reset' %}">Lost password?</a>
          </p>

            {% endif %}

		  <form class="navbar-form navbar-right" role="form" method="post" action="{% url 'questionnaires:loginform' %}">
              {% csrf_token %}
              <span><i class="glyphicon glyphicon-user"></i></span><div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Username">
              </div>
              <span><i class="glyphicon glyphicon-lock"></i></span>
              <div class="form-group"><input type="password" class="form-control" name="password" placeholder="Password">
              </div>
              <button type="submit" class="btn btn-primary">Sign In</button>
          </form>
        {% endif %}
	  </div>
	</nav>
	 <div class="container content">
	{% block sidebar %}{% endblock %}
	{% block content %}{% endblock %}
	</div>
	<footer>
        {% block footer_navigation %}
            {% include "questionnaires/footer_navbar.html" %}
        {% endblock %}
            <p>Copyright (c) 2016 Queensland Brain Institute</p>
        </footer>
    </body>
</html>

questionnaires/templates/questionnaires/confirm_delete.html
{% extends "questionnaires/base.html" %}
{% block title %}Delete{% endblock %}
{% block content %}
<div class="container">
<div class="page-header">
    <h2>Delete Test Result</h2></div>
    <div class="row col-md-6">
    <div class="well">
    <form role="form" method="post">{% csrf_token %}
        {% if msg  %}
           <p class="info"> {{ msg|force_escape }}</p>
        {% else %}
            <p>Are you sure you want to delete this test result?</p>
        <ul><li>Questionnaire: {{qnaire.title|force_escape}}</li>
        <li>Subject: {{subject.username|force_escape}}</li>
        <li>Timestamp: {{date}}</li></ul>
            <input type="submit" class="btn btn-success" value="Confirm" />
            <input type="button" class="btn btn-default" onclick="javascript:history.back();return false;" value="Cancel" />
        {% endif %}

    </form>
    </div></div></div>
{% endblock %}

questionnaires/templates/questionnaires/done.html
{% extends "questionnaires/base.html" %}
{% block content %}

<div class="jumbotron text-center container-fluid">
    <h1><span class="glyphicon glyphicon-check"></span>Questionnaire Complete</h1>
    {% if user.subjectvisit.icon %}
    <div class="row text-center slideanim">
    <img align="center" width="300px" src="/media/{{user.subjectvisit.icon}}" alt="{{user.firstname}}"/>
        </div>
    {% endif %}
    <p>Thanks for completing the {{qnaire_title}} questionnaire</p>




</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            {% if followup %}
            <p><a href="{% url 'questionnaires:qintro' followup %}" class="btn btn-primary"> Proceed to next questionnaire in this series <span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
            {% endif %}

            <p><a href="/questionnaires" class="btn btn-success"> Return to Home <span
                class="glyphicon glyphicon-circle-arrow-up"></span></a></p>
        </div>
    </div>
</div>
{% endblock content %}

questionnaires/templates/questionnaires/footer_navbar.html
<div id="navigation" data-role="navbar">
<p align="center"><a href="mailto:e.cooperwilliams@uq.edu.au?subject=QTAB%20Database%20Website%20Enquiry" title="Contact QTAB Database Administrator"><span class="glyphicon glyphicon-envelope"></span> Contact QTAB Database Administrator</a></p>
</div>

questionnaires/templates/questionnaires/index.html
{% extends "questionnaires/base.html" %}
{% block content %}{% load staticfiles %}
<div class="container">
    <div class="jumbotron">
        <span><img src="{% static "qtab/img/logo.png" %}" align="center" alt="QBI, The University of Queensland"/></span>
        {%if user.subjectvisit.icon %}

        <img align="right" width="200px" src="/media/{{user.subjectvisit.icon}}" alt="{{user.first_name}}"/>

        {% endif %}
        <h1>Welcome to the <br/>Queensland Twin Adolescent Brain Study</h1>
        {% if not user.is_authenticated %}
        <p>Please sign in so you can access your questionnaires.</p>

        {% endif %}


    </div>
{% if user.is_authenticated %}

    <div class="row">

        <div class="col-sm-6">
            <div class="well table-responsive">
                {% if user.is_staff %}
                <h3>Questionnaires to do</h3>
                {% else %}
                <h3>My Questionnaires for {{visit.name|force_escape}}</h3>
                {% endif %}
                {% if questionnaire_list %}
                <table class="table table-condensed">
                    <thead>
                    <tr>

                        <th>Questionnaire</th>
                        <th>Qns</th>
                        <th>Visit</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for q in questionnaire_list %}
                    <tr>

                        <td><a href="{% url 'questionnaires:qintro' q.id %}" class="btn btn-success allowwrap">{{q}} <span class="glyphicon glyphicon-circle-arrow-right"></span></a></td>
                        <td>{{q.question_set.count}}</td>
                        <td><span class="badge allowwrap">{{ q.categorylist}}</span></td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
                {% else %}
                <p>No questionnaires to do</p>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="well">
                <h3>My Completed Questionnaires</h3>
                {% if result_list %}
                <table class="table table-condensed table-responsive">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Date</th>
                        <th>Questionnaire</th>
                        <th>Category</th>
                        <th></th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for q in result_list %}
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-check"></span></td>
                        <td>{{q.date_stored|date:"d-M-Y"}}</td>
                        <td>{{q.questionnaire.title|force_escape}}</td>
                        <td>{{q.questionnaire.categorylist}}</td>
                        <td><a href="{% url 'questionnaires:qintro' q.questionnaire.id %}" class="btn btn-primary btn-small" title="Repeat Questionnaire"><span class="glyphicon glyphicon-refresh"></span></a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>No questionnaires completed</p>
                {% endif %}

            </div>
        </div>


    </div>
{% endif %}

</div>
{% endblock %}

questionnaires/templates/questionnaires/intro.html
{% extends "questionnaires/base.html" %}
{% block content %}
<h1>{{ object.title|safe }}</h1>
<small>Date: {{ now|date:"d M Y" }}</small>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="well col-md-6">
            <p>{{ object.intropage|safe }}</p>
            <div align="right"><a href="{% url 'questionnaires:q' object.id %}" class="btn btn-success"><h4>Start <span
                            class="glyphicon glyphicon-circle-arrow-right"></span></h4></a></div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

{% endblock content %}

questionnaires/templates/questionnaires/locked.html
{% extends "questionnaires/base.html" %}
{% block content %}
<div class="container">
<h3>Sorry, you've been locked out due to failed password attempts</h3>
    <p>To reset, please enter the captcha below</p>
<form action="" method="post">
    {% csrf_token %}

    {{ form.captcha.errors }}
    {{ form.captcha }}

    <div class="form-actions">
        <input type="submit" value="Submit" />
    </div>
</form>

</div>
{% endblock %}

questionnaires/templates/questionnaires/navlinks.html
<li><a href="{% url 'admin:index' %}" class="ui-btn-active">Admin</a></li>
<li><a href="{% url 'questionnaires:reports' %}">Reports</a></li>
<li><a href="{% url 'questionnaires:results' %}">Results</a></li>
<li><a href="{% url 'questionnaires:visits' %}">Visits</a></li>

questionnaires/templates/questionnaires/report.html
{% extends "questionnaires/base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
<div class="container">
    <h1>{{qtitle}}</h1>
    <div class="row">
        <div class="col-sm-12">
            <div class="well">

            {% render_table table %}

            </div>
            </div>
        </div>
</div>
{% endblock content %}

questionnaires/templates/questionnaires/results.html
{% extends "questionnaires/base.html" %}
{% load i18n %}

{% block title %}Questionnaires completed{% endblock %}
{% block content %}{% load staticfiles %}


<div class="container">

        {% if results_table %}
    <div class="panel panel-info">
        <div class="panel-heading"><h3 class="panel-title">Questionnaires completed</h3></div>
        <div class="panel-body">

            <table class="table">
                <thead>
                <tr>
                    <th>Questionnaire</th>
                    <th>Question</th>
                    <th>Choice</th>
                    <th>Count</th>
                </tr>
                </thead>
                <tbody>
                {% for result in results_table %}
                <tr>
                    <td>{{result.question.qid.title|force_escape}}</td>
                    <td>{{result.question.question_text|force_escape}}</td>
                    <td>{{result.choice_text|force_escape}}</td>
                    <td>{{result.choice_count|force_escape}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

questionnaires/templates/questionnaires/results_summary.html
{% extends "questionnaires/base.html" %}
{% load i18n %}
{% load django_tables2 %}
{% block title %}Questionnaire results{% endblock %}

{% block content %}
<div class="sidebar">
   <div class="well col-xs-8">
    <button data-toggle="collapse" class="btn btn-small btn-primary" data-target="#searchform"><h4>Search Results</h4></button>
       <div id="searchform" class="collapse">
           <br/>
            <form method='GET'>
                {{ filter.form.as_p }}
                <br/>
                <input type='submit' class="btn btn-info" value='Search'/>
                <a href='{{ request.path }}' class="btn btn-default">Clear</a>
                <br/>
                <div class="small">|&nbsp;
                Displaying {{ filter.qs|length }} of {{ filter.queryset|length }} items.
                &nbsp;|</div>

            </form>
       </div>
    </div>

</div>
<div class="container">
    <div class="row col-xs-12">
    {% if table %}
    <div class="panel panel-info">
        <div class="panel-heading"><h3 class="panel-title">{{title}}</h3></div>
        <div class="panel-body">
            {% render_table table %}

        </div>
    </div>
    {% endif %}
</div></div>
{% endblock content %}